"""
BAHAWAL CARDIOLOGIST HOSPITAL — Heart Disease Risk Prediction API
=================================================================

This is a drop-in replacement for the original Azure-deployed API. It exposes
the same `/predict` contract your n8n workflow + hospital frontend expect.

Endpoints
---------
  GET  /                  → service info + model card
  GET  /health            → liveness probe (used by UptimeRobot)
  GET  /model-info        → feature order + defaults
  POST /predict           → main prediction endpoint
  GET  /docs              → Swagger UI (auto-generated by FastAPI)
  GET  /frontend          → simple HTML form for ad-hoc testing

Predict contract
----------------
  Request body (8 features from n8n workflow):
    {
      "age":      int,
      "trestbps": int,    // resting blood pressure
      "chol":     int,    // cholesterol mg/dL
      "cp":       int,    // chest pain type 0-3
      "ca":       int,    // major vessels (0-3) colored by fluoroscopy
      "thalach":  int,    // max heart rate
      "thal":     int,    // thalassemia 0-3
      "oldpeak":  float   // ST depression
    }

  Response:
    { "risk_probability": 0.73 }   // 0.0 → no risk, 1.0 → high risk

  Internally the model needs 14 features; missing ones (sex, fbs, restecg,
  exang, slope) are filled with population defaults loaded from
  `feature_defaults.json`. `trestbps_capped` is derived.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Load model + metadata at startup
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent
ARTIFACT_DIR = BASE_DIR / "model_artifacts"

model = joblib.load(ARTIFACT_DIR / "heart_rf_model.joblib")
feature_columns: list[str] = joblib.load(ARTIFACT_DIR / "feature_columns.joblib")
with open(ARTIFACT_DIR / "feature_defaults.json") as f:
    feature_defaults: dict[str, int] = json.load(f)

# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------
app = FastAPI(
    title="BAHAWAL CARDIOLOGIST HOSPITAL — Heart Risk API",
    description=(
        "Random Forest classifier predicting heart disease risk from 8 clinical "
        "features. Trained on the Cleveland heart disease dataset (1,025 patients). "
        "Returns a risk probability in [0, 1]."
    ),
    version="2.0.0",
    contact={"name": "BAHAWAL CARDIOLOGIST HOSPITAL", "url": "https://bahawal-heartcare-hospital.logicrun.online/"},
)

# Open CORS so the hospital frontend (and n8n) can call us from any origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------
class PredictRequest(BaseModel):
    age:      int = Field(..., ge=1,   le=120, description="Patient age in years")
    trestbps: int = Field(..., ge=50,  le=250, description="Resting blood pressure (mm Hg)")
    chol:     int = Field(..., ge=100, le=600, description="Serum cholesterol (mg/dL)")
    cp:       int = Field(..., ge=0,   le=3,   description="Chest pain type (0-3)")
    ca:       int = Field(..., ge=0,   le=4,   description="Number of major vessels (0-4) colored by fluoroscopy")
    thalach:  int = Field(..., ge=50,  le=250, description="Maximum heart rate achieved (bpm)")
    thal:     int = Field(..., ge=0,   le=3,   description="Thalassemia type (0-3)")
    oldpeak:  float = Field(..., ge=0, le=7, description="ST depression induced by exercise relative to rest")


class PredictResponse(BaseModel):
    risk_probability: float = Field(..., description="Probability of heart disease in [0, 1]")
    risk_level:       str   = Field(..., description="Low / Moderate / High")
    model_version:    str
    disclaimer:       str


# silence pydantic warning about `model_version` colliding with the protected namespace
PredictResponse.model_config = {"protected_namespaces": ()}  # type: ignore[attr-defined]


# ---------------------------------------------------------------------------
# Full-form schema: what the hospital frontend already sends to the n8n webhook.
# We accept the same shape so the frontend only needs to change ONE URL.
# ---------------------------------------------------------------------------
class PatientInfo(BaseModel):
    full_name:    str
    email:        str
    phone:        str
    date_of_birth: str   # ISO date string, e.g. "1970-05-12"


class MedicalData(BaseModel):
    trestbps: float
    chol:     float
    cp:       float
    ca:       float
    thalach:  float
    thal:     float
    oldpeak:  float


class HospitalFormRequest(BaseModel):
    patient_info: PatientInfo
    medical_data: MedicalData


class HospitalFormResponse(BaseModel):
    success:            bool
    risk_probability:   float
    risk_score:         int           # 0–100
    risk_level:         str           # Moderate / High / Very High (frontend expects this)
    risk_category:      str           # same value, plural-safety
    has_heart_disease:  bool
    recommendation:     str           # frontend expects this
    recommendations:    str           # plural variant
    alert_level:        str           # normal / high / critical
    timestamp:          str
    request_id:         str
    disclaimer:         str
    model_version:      str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _build_feature_row(payload: dict[str, Any]) -> pd.DataFrame:
    """Merge the 8 caller-supplied features with the 5 defaults + derived trestbps_capped."""
    row = {**feature_defaults, **payload}
    row["trestbps_capped"] = min(int(row["trestbps"]), 200)
    # Order columns EXACTLY as the model was trained on
    return pd.DataFrame([row], columns=feature_columns)


def _classify(p: float) -> str:
    if p < 0.30:
        return "Low"
    if p < 0.60:
        return "Moderate"
    return "High"


def _classify_full(p: float) -> str:
    """Match the n8n workflow's 3-bucket scheme so the frontend rendering is unchanged."""
    if p < 0.5:
        return "Moderate"
    if p < 0.7:
        return "High"
    return "Very High"


def _age_from_dob(dob: str) -> int:
    from datetime import datetime, date
    try:
        d = datetime.fromisoformat(dob.replace("Z", "")).date()
    except ValueError:
        d = date.fromisoformat(dob)
    today = date.today()
    return today.year - d.year - ((today.month, today.day) < (d.month, d.day))


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/api-info")
def root() -> dict:
    return {
        "service": "BAHAWAL CARDIOLOGIST HOSPITAL — Heart Risk API",
        "model":   "Random Forest (Cleveland dataset, 1,025 patients)",
        "version": "2.0.0",
        "endpoints": {
            "predict":     "POST /predict       (8 model features)",
            "predict_full":"POST /predict-full  (hospital form JSON, no n8n needed)",
            "model_info":  "GET  /model-info",
            "health":      "GET  /health",
            "docs":        "GET  /docs",
            "frontend":    "GET  /frontend",
            "ui":          "GET  /             → the full hospital React app",
        },
    }


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "model_loaded": model is not None}


@app.get("/model-info")
def model_info() -> dict:
    return {
        "model_type":        type(model).__name__,
        "n_features":        model.n_features_in_,
        "feature_order":     feature_columns,
        "feature_defaults":  feature_defaults,
        "feature_importances": {
            name: float(imp) for name, imp in zip(feature_columns, model.feature_importances_)
        },
    }


@app.post("/predict", response_model=PredictResponse)
def predict(req: PredictRequest) -> PredictResponse:
    try:
        X = _build_feature_row(req.model_dump())
        proba = float(model.predict_proba(X)[0][1])  # P(class=1)
        return PredictResponse(
            risk_probability=round(proba, 4),
            risk_level=_classify(proba),
            model_version="2.0.0-rf",
            disclaimer=(
                "This is a risk estimation tool only. "
                "It does NOT provide medical diagnosis. "
                "All final decisions must be made by qualified healthcare professionals."
            ),
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {e!s}") from e


# ---------------------------------------------------------------------------
# Hospital-front-end-facing endpoint. Accepts the same JSON the old n8n webhook
# used to accept so the frontend only has to change ONE URL.
# ---------------------------------------------------------------------------
@app.post("/predict-full", response_model=HospitalFormResponse)
def predict_full(req: HospitalFormRequest) -> HospitalFormResponse:
    try:
        age = _age_from_dob(req.patient_info.date_of_birth)
        md = req.medical_data.model_dump()

        payload = {
            "age":      age,
            "trestbps": float(md["trestbps"]),
            "chol":     float(md["chol"]),
            "cp":       float(md["cp"]),
            "ca":       float(md["ca"]),
            "thalach":  float(md["thalach"]),
            "thal":     float(md["thal"]),
            "oldpeak":  float(md["oldpeak"]),
        }
        X = _build_feature_row(payload)
        proba = float(model.predict_proba(X)[0][1])

        # Build the same 3-tier breakdown the old n8n workflow produced
        if proba < 0.5:
            category, alert, rec = "Moderate", "normal", "Schedule a routine check-up with your doctor"
        elif proba < 0.7:
            category, alert, rec = "High", "high", "Consult a cardiologist within 2 weeks"
        else:
            category, alert, rec = "Very High", "critical", "IMMEDIATE cardiology consultation required!"

        from datetime import datetime, timezone
        import uuid

        return HospitalFormResponse(
            success=True,
            risk_probability=round(proba, 4),
            risk_score=int(round(proba * 100)),
            # The Lovable-built hospital frontend reads BOTH spellings
            risk_level=category,          # ← what the frontend expects
            risk_category=category,       # ← kept for backwards compat
            has_heart_disease=proba >= 0.5,
            recommendation=rec,           # ← what the frontend expects
            recommendations=rec,          # ← plural variant the frontend also checks
            alert_level=alert,
            timestamp=datetime.now(timezone.utc).isoformat(),
            request_id=f"{int(datetime.now(timezone.utc).timestamp() * 1000)}-{uuid.uuid4().hex[:6]}",
            disclaimer=(
                "This is a risk estimation tool only. "
                "It does NOT provide medical diagnosis. "
                "All final decisions must be made by qualified healthcare professionals."
            ),
            model_version="2.0.0-rf",
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {e!s}") from e


# ---------------------------------------------------------------------------
# Minimal in-browser test UI (so the API is usable without the hospital frontend)
# ---------------------------------------------------------------------------
@app.get("/frontend")
def frontend():
    html = BASE_DIR / "frontend" / "index.html"
    if not html.exists():
        return JSONResponse({"error": "frontend not bundled"}, status_code=404)
    return FileResponse(html)


# ---------------------------------------------------------------------------
# Hospital frontend — the patched build of the user's Lovable app is bundled
# here so the whole system lives at one URL: API + Swagger + the React app.
# ---------------------------------------------------------------------------
from fastapi.staticfiles import StaticFiles
from starlette.responses import FileResponse as _FileResponse

STATIC_DIR = BASE_DIR / "static_frontend"
if STATIC_DIR.exists():
    # Serve assets (JS, CSS, images) directly
    app.mount("/assets", StaticFiles(directory=str(STATIC_DIR / "assets")), name="assets")

    @app.get("/", response_class=HTMLResponse)
    @app.get("/{path:path}", response_class=HTMLResponse, include_in_schema=False)
    def spa_fallback(path: str = ""):
        """SPA fallback — every non-API route returns index.html so client-side
        routing (React Router) can take over. /assets/* are served by the mount above."""
        # Don't intercept real API/docs/frontend paths
        if path.startswith(("predict", "health", "model-info", "docs", "openapi", "frontend", "assets")):
            return JSONResponse({"detail": "Not Found"}, status_code=404)
        index = STATIC_DIR / "index.html"
        if index.exists():
            return _FileResponse(index)
        return JSONResponse({"error": "frontend dist not found"}, status_code=404)


# ---------------------------------------------------------------------------
# Local dev entrypoint
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("app:app", host="0.0.0.0", port=port, reload=False)
